// fn_library_index.js
// Punto de Entrada Principal e Índice Unificado de la Librería de Funciones Categorizada

import * as DOMUI from './fn_dom_ui.js';
import * as GraphicsCanvas from './fn_graphics_canvas.js';
import * as AudioCore from './fn_audio.js';
import * as AudioPro from './fn_audio2.js';
import * as Spatial from './fn_spatial.js';
import * as WorldChunks from './fn_world_chunks.js';
import * as GameCore from './fn_game_core.js';
import * as Math3D from './fn_math_3d.js';
import * as WorldChunks3D from './fn_world_chunks3d.js';
import * as Physics3D from './fn_physics_3d.js';
export { DOMUI, GraphicsCanvas, AudioCore, AudioPro, Spatial, WorldChunks, GameCore };

export const UNIFIED_FUNCTION_LIBRARY = [
  // --- GRUPO 1: DOM & UI (fn_dom_ui.js) ---
  {
    id: 'fn_createElement',
    name: 'createElement',
    tags: ['UI', 'DOM'],
    signature: 'createElement(tag: string, attrs?: Record<string, any>, children?: string | Array<HTMLElement | string>): HTMLElement',
    desc: 'Crea elementos HTML con atributos, eventos inline, clases y componentes hijos.',
    javascript_code: DOMUI.createElement.toString(),
  },
  {
    id: 'fn_qs',
    name: 'qs',
    tags: ['UI', 'DOM'],
    signature: 'qs(selector: string, scope?: HTMLElement | Document): HTMLElement | null',
    desc: 'Wrapper rápido de querySelector.',
    javascript_code: DOMUI.qs.toString(),
  },
  {
    id: 'fn_qsa',
    name: 'qsa',
    tags: ['UI', 'DOM'],
    signature: 'qsa(selector: string, scope?: HTMLElement | Document): Array<HTMLElement>',
    desc: 'Wrapper de querySelectorAll devuelto como Array.',
    javascript_code: DOMUI.qsa.toString(),
  },
  {
    id: 'fn_addClass',
    name: 'addClass',
    tags: ['UI', 'DOM'],
    signature: 'addClass(el: HTMLElement, className: string): void',
    desc: 'Añade una o varias clases CSS a un elemento DOM.',
    javascript_code: DOMUI.addClass.toString(),
  },
  {
    id: 'fn_removeClass',
    name: 'removeClass',
    tags: ['UI', 'DOM'],
    signature: 'removeClass(el: HTMLElement, className: string): void',
    desc: 'Elimina clases CSS de un elemento DOM.',
    javascript_code: DOMUI.removeClass.toString(),
  },
  {
    id: 'fn_toggleClass',
    name: 'toggleClass',
    tags: ['UI', 'DOM'],
    signature: 'toggleClass(el: HTMLElement, className: string, force?: boolean): boolean',
    desc: 'Alterna o fuerza el estado de una clase CSS en un elemento.',
    javascript_code: DOMUI.toggleClass.toString(),
  },
  {
    id: 'fn_showToast',
    name: 'showToast',
    tags: ['UI', 'DOM'],
    signature: "showToast(message: string, type?: 'info' | 'success' | 'error' | 'warning', duration?: number): void",
    desc: 'Muestra notificaciones emergentes temporales en pantalla.',
    javascript_code: DOMUI.showToast.toString(),
  },
  {
    id: 'fn_createModal',
    name: 'createModal',
    tags: ['UI', 'DOM'],
    signature: 'createModal(options: { title: string, content: HTMLElement | string, onClose?: () => void }): { overlay: HTMLElement, modal: HTMLElement, close: () => void }',
    desc: 'Genera una ventana modal flotante personalizable.',
    javascript_code: DOMUI.createModal.toString(),
  },
  {
    id: 'fn_makeDraggable',
    name: 'makeDraggable',
    tags: ['UI', 'DOM'],
    signature: 'makeDraggable(element: HTMLElement, handle?: HTMLElement): void',
    desc: 'Hace un elemento flotante arrastrable por el cursor mediante mouse events.',
    javascript_code: DOMUI.makeDraggable.toString(),
  },
  {
    id: 'fn_makeResizable',
    name: 'makeResizable',
    tags: ['UI', 'DOM'],
    signature: 'makeResizable(element: HTMLElement): void',
    desc: 'Añade tirador en la esquina inferior para redimensionar un elemento DOM.',
    javascript_code: DOMUI.makeResizable.toString(),
  },
  {
    id: 'fn_copyToClipboard',
    name: 'copyToClipboard',
    tags: ['UI', 'Utils'],
    signature: 'copyToClipboard(text: string): Promise<boolean>',
    desc: 'Copia texto al portapapeles usando Clipboard API con fallback.',
    javascript_code: DOMUI.copyToClipboard.toString(),
  },
  {
    id: 'fn_injectStyle',
    name: 'injectStyle',
    tags: ['UI', 'DOM'],
    signature: 'injectStyle(cssText: string, id?: string): HTMLStyleElement',
    desc: 'Inyecta código CSS dinámico directamente en la cabecera del documento.',
    javascript_code: DOMUI.injectStyle.toString(),
  },

  // --- GRUPO 2: GRAPHICS & CANVAS (fn_graphics_canvas.js) ---
  {
    id: 'fn_fitCanvasToParent',
    name: 'fitCanvasToParent',
    tags: ['Graphics', 'Canvas'],
    signature: 'fitCanvasToParent(canvas: HTMLCanvasElement, aspectRatio?: number): void',
    desc: 'Ajusta el lienzo Canvas al contenedor padre respetando o no un aspecto relacional.',
    javascript_code: GraphicsCanvas.fitCanvasToParent.toString(),
  },
  {
    id: 'fn_clearCanvas',
    name: 'clearCanvas',
    tags: ['Graphics', 'Canvas'],
    signature: 'clearCanvas(ctx: CanvasRenderingContext2D): void',
    desc: 'Limpia completamente el lienzo de dibujo 2D.',
    javascript_code: GraphicsCanvas.clearCanvas.toString(),
  },
  {
    id: 'fn_drawRotatedSprite',
    name: 'drawRotatedSprite',
    tags: ['Graphics', 'Canvas'],
    signature: 'drawRotatedSprite(ctx: CanvasRenderingContext2D, img: HTMLImageElement, x: number, y: number, angle?: number, scale?: number): void',
    desc: 'Dibuja un sprite en el lienzo rotado alrededor de su centro y escalado.',
    javascript_code: GraphicsCanvas.drawRotatedSprite.toString(),
  },
  {
    id: 'fn_drawGradientRect',
    name: 'drawGradientRect',
    tags: ['Graphics', 'Canvas'],
    signature: 'drawGradientRect(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, colors?: Array<string>, angle?: number): void',
    desc: 'Dibuja rectángulos con degradados lineales dinámicos.',
    javascript_code: GraphicsCanvas.drawGradientRect.toString(),
  },
  {
    id: 'fn_drawRoundedRect',
    name: 'drawRoundedRect',
    tags: ['Graphics', 'Canvas'],
    signature: 'drawRoundedRect(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, radius?: number, fill?: boolean, stroke?: boolean): void',
    desc: 'Dibuja rectángulos con bordes redondeados en Canvas.',
    javascript_code: GraphicsCanvas.drawRoundedRect.toString(),
  },
  {
    id: 'fn_drawProceduralCircle',
    name: 'drawProceduralCircle',
    tags: ['Graphics', 'Canvas'],
    signature: 'drawProceduralCircle(ctx: CanvasRenderingContext2D, x: number, y: number, radius: number, strokeColor?: string, fillColor?: string): void',
    desc: 'Dibuja círculos procedurales con opciones de relleno y trazo.',
    javascript_code: GraphicsCanvas.drawProceduralCircle.toString(),
  },
  {
    id: 'fn_getCanvasPixelColor',
    name: 'getCanvasPixelColor',
    tags: ['Graphics', 'Canvas'],
    signature: 'getCanvasPixelColor(ctx: CanvasRenderingContext2D, x: number, y: number): { r: number, g: number, b: number, a: number, rgba: string }',
    desc: 'Obtiene el color y canal alfa exacto de un píxel en Canvas.',
    javascript_code: GraphicsCanvas.getCanvasPixelColor.toString(),
  },
  {
    id: 'fn_exportCanvasToBlob',
    name: 'exportCanvasToBlob',
    tags: ['Graphics', 'Canvas'],
    signature: "exportCanvasToBlob(canvas: HTMLCanvasElement, type?: string, quality?: number): Promise<Blob>",
    desc: 'Exporta el renderizado de Canvas a un objeto Blob binario.',
    javascript_code: GraphicsCanvas.exportCanvasToBlob.toString(),
  },
  {
    id: 'fn_applyCanvasFilter',
    name: 'applyCanvasFilter',
    tags: ['Graphics', 'Canvas'],
    signature: 'applyCanvasFilter(ctx: CanvasRenderingContext2D, filterString: string): void',
    desc: 'Aplica filtros CSS (blur, brightness, contrast) directamente sobre el contexto Canvas.',
    javascript_code: GraphicsCanvas.applyCanvasFilter.toString(),
  },
  {
    id: 'fn_createTileMapRenderer',
    name: 'createTileMapRenderer',
    tags: ['Graphics', 'Canvas', 'GameCore'],
    signature: 'createTileMapRenderer(ctx: CanvasRenderingContext2D, mapData: Array<Array<number>>, tileSize: number, spritesheet: HTMLImageElement): (offsetX?: number, offsetY?: number) => void',
    desc: 'Renderizador optimizado de mapas de azulejos (Tilemaps) 2D.',
    javascript_code: GraphicsCanvas.createTileMapRenderer.toString(),
  },

  // --- GRUPO 3: AUDIO CORE & PRO (fn_audio.js & fn_audio2.js) ---
  {
    id: 'fn_initAudioContext',
    name: 'initAudioContext',
    tags: ['Audio'],
    signature: 'initAudioContext(): AudioContext',
    desc: 'Inicializa y reanuda el contexto de Web Audio API con bus maestro y limitador de picos de seguridad.',
    javascript_code: AudioCore.initAudioContext.toString(),
  },
  {
    id: 'fn_getMasterAudioDestination',
    name: 'getMasterAudioDestination',
    tags: ['Audio'],
    signature: 'getMasterAudioDestination(): AudioNode | null',
    desc: 'Obtiene el nodo de destino maestro (con limitador de distorsión digital).',
    javascript_code: AudioCore.getMasterAudioDestination.toString(),
  },
  {
    id: 'fn_playTone',
    name: 'playTone',
    tags: ['Audio'],
    signature: "playTone(freq: number, duration?: number, type?: 'sine' | 'square' | 'sawtooth' | 'triangle', volume?: number): void",
    desc: 'Reproduce tonos y frecuencias sintéticas de forma inmediata.',
    javascript_code: AudioCore.playTone.toString(),
  },
  {
    id: 'fn_playSFXJump',
    name: 'playSFXJump',
    tags: ['Audio', 'GameCore'],
    signature: 'playSFXJump(): void',
    desc: 'Efecto de sonido sintético de salto retro/8-bit.',
    javascript_code: AudioCore.playSFXJump.toString(),
  },
  {
    id: 'fn_playSFXExplosion',
    name: 'playSFXExplosion',
    tags: ['Audio', 'GameCore'],
    signature: 'playSFXExplosion(): void',
    desc: 'Efecto de sonido sintético de explosión/impacto con ruido filtrado.',
    javascript_code: AudioCore.playSFXExplosion.toString(),
  },
  {
    id: 'fn_playSFXCoin',
    name: 'playSFXCoin',
    tags: ['Audio', 'GameCore'],
    signature: 'playSFXCoin(): void',
    desc: 'Efecto de sonido sintético retro de recolección de moneda/ítem.',
    javascript_code: AudioCore.playSFXCoin.toString(),
  },
  {
    id: 'fn_createSimpleSynth',
    name: 'createSimpleSynth',
    tags: ['Audio'],
    signature: 'createSimpleSynth(): { triggerAttackRelease: (freq: number, duration?: number, adsr?: { a: number, d: number, s: number, r: number }) => void }',
    desc: 'Sintetizador con envolvente ADSR personalizable.',
    javascript_code: AudioCore.createSimpleSynth.toString(),
  },
  {
    id: 'fn_createAudioAnalyser',
    name: 'createAudioAnalyser',
    tags: ['Audio', 'Graphics'],
    signature: 'createAudioAnalyser(audioCtx: AudioContext, sourceNode?: AudioNode, fftSize?: number): AnalyserNode',
    desc: 'Analizador FFT en tiempo real para visualizadores de audio.',
    javascript_code: AudioCore.createAudioAnalyser.toString(),
  },
  {
    id: 'fn_getFrequencyData',
    name: 'getFrequencyData',
    tags: ['Audio'],
    signature: 'getFrequencyData(analyser: AnalyserNode): Uint8Array',
    desc: 'Extrae datos de frecuencia binaria para renderizado visual de ondas/espectro.',
    javascript_code: AudioCore.getFrequencyData.toString(),
  },
  {
    id: 'fn_setMasterVolume',
    name: 'setMasterVolume',
    tags: ['Audio'],
    signature: 'setMasterVolume(gainNode?: GainNode, volume?: number): void',
    desc: 'Ajusta el volumen maestro general del sistema de sonido.',
    javascript_code: AudioCore.setMasterVolume.toString(),
  },
  {
    id: 'fn_loadAudioBuffer',
    name: 'loadAudioBuffer',
    tags: ['Audio'],
    signature: 'loadAudioBuffer(url: string): Promise<AudioBuffer>',
    desc: 'Carga y decodifica archivos de audio vía fetch a Web Audio API.',
    javascript_code: AudioCore.loadAudioBuffer.toString(),
  },
  {
    id: 'fn_createDistortionCurve',
    name: 'createDistortionCurve',
    tags: ['Audio', 'AudioPro'],
    signature: 'createDistortionCurve(amount?: number): Float32Array',
    desc: 'Genera curvas de distorsión/overdrive para WaveShaperNode.',
    javascript_code: AudioPro.createDistortionCurve.toString(),
  },
  {
    id: 'fn_playFMTone',
    name: 'playFMTone',
    tags: ['Audio', 'AudioPro'],
    signature: 'playFMTone(options: { carrierFreq?: number, modulatorFreq?: number, modulationIndex?: number, duration?: number, carrierType?: string, modulatorType?: string, distortion?: number, volume?: number }): void',
    desc: 'Sintetizador FM de 2 operadores para efectos complejos, bajos y sci-fi.',
    javascript_code: AudioPro.playFMTone.toString(),
  },
  {
    id: 'fn_playCinematicImpact',
    name: 'playCinematicImpact',
    tags: ['Audio', 'AudioPro'],
    signature: "playCinematicImpact(options?: { type?: 'sub_drop' | 'cyber_blast' | 'metal_hit', volume?: number }): void",
    desc: 'Generador de impactos cinematográficos y caídas de sub-graves.',
    javascript_code: AudioPro.playCinematicImpact.toString(),
  },
  {
    id: 'fn_synthesizeCustomPatch',
    name: 'synthesizeCustomPatch',
    tags: ['Audio', 'AudioPro'],
    signature: 'synthesizeCustomPatch(patchConfig: Record<string, any>): void',
    desc: 'Motor de parches sintetizados avanzados recibiendo configuraciones JSON complejas.',
    javascript_code: AudioPro.synthesizeCustomPatch.toString(),
  },

  // --- GRUPO 4: GAME CORE (fn_game_core.js) ---
  {
    id: 'fn_createGameLoop',
    name: 'createGameLoop',
    tags: ['GameCore', 'Physics'],
    signature: 'createGameLoop(options: { update: (dt: number) => void, render: (alpha: number) => void, targetFps?: number }): { start: () => void, stop: () => void }',
    desc: 'Bucle de juego con acumulador temporal y compensación estricta de DeltaTime.',
    javascript_code: GameCore.createGameLoop.toString(),
  },
  {
    id: 'fn_createStateMachine',
    name: 'createStateMachine',
    tags: ['GameCore'],
    signature: 'createStateMachine(initialState?: string): { addState: (name: string, config: { onEnter?: (payload?: any) => void, onUpdate?: (dt: number) => void, onExit?: () => void }) => void, changeState: (name: string, payload?: any) => void, update: (dt: number) => void, getCurrentState: () => string }',
    desc: 'Máquina de estados finitos (FSM) para controlar el flujo del juego.',
    javascript_code: GameCore.createStateMachine.toString(),
  },
  {
    id: 'fn_createInputManager',
    name: 'createInputManager',
    tags: ['GameCore', 'Input'],
    signature: 'createInputManager(targetElement?: HTMLElement | Window): { isKeyDown: (code: string) => boolean, getMouse: () => { x: number, y: number, isDown: boolean, clicked: boolean }, destroy: () => void }',
    desc: 'Gestor unificado de entradas para teclado y ratón.',
    javascript_code: GameCore.createInputManager.toString(),
  },
  {
    id: 'fn_applyPhysics2D',
    name: 'applyPhysics2D',
    tags: ['GameCore', 'Physics'],
    signature: 'applyPhysics2D(entity: { x: number, y: number, vx?: number, vy?: number, ax?: number, ay?: number }, dt: number, options?: { gravity?: number, friction?: number, maxSpeedX?: number, maxSpeedY?: number }): void',
    desc: 'Aplica física Euler simple con fricción y gravedad sobre una entidad 2D.',
    javascript_code: GameCore.applyPhysics2D.toString(),
  },
  {
    id: 'fn_resolveAABBCollision',
    name: 'resolveAABBCollision',
    tags: ['GameCore', 'Physics'],
    signature: 'resolveAABBCollision(rectA: { x: number, y: number, w: number, h: number, vx?: number, vy?: number }, rectB: { x: number, y: number, w: number, h: number }, bounce?: number): "horizontal" | "vertical" | null',
    desc: 'Resuelve e impulsa la respuesta física de colisión entre dos cajas AABB.',
    javascript_code: GameCore.resolveAABBCollision.toString(),
  },
  {
    id: 'fn_mathLerp',
    name: 'mathLerp',
    tags: ['GameCore', 'Utils'],
    signature: 'mathLerp(a: number, b: number, t: number): number',
    desc: 'Interpolación lineal entre dos puntos.',
    javascript_code: GameCore.mathLerp.toString(),
  },
  {
    id: 'fn_mathClamp',
    name: 'mathClamp',
    tags: ['GameCore', 'Utils'],
    signature: 'mathClamp(value: number, min: number, max: number): number',
    desc: 'Restringe un valor dentro de un rango mínimo y máximo.',
    javascript_code: GameCore.mathClamp.toString(),
  },

  // --- GRUPO 5: SPATIAL & WORLD CHUNKS (fn_spatial.js & fn_world_chunks.js) ---
  {
    id: 'fn_SpatialHashGrid',
    name: 'SpatialHashGrid',
    tags: ['Physics', 'Spatial'],
    signature: 'new SpatialHashGrid(bounds: { x: number, y: number, w: number, h: number }, cellSize?: number)',
    desc: 'Grilla de particionado espacial para optimizar consultas de colisión O(1).',
    javascript_code: Spatial.SpatialHashGrid.toString(),
  },
  {
    id: 'fn_isAABBIntersecting',
    name: 'isAABBIntersecting',
    tags: ['Physics', 'Spatial'],
    signature: 'isAABBIntersecting(rectA: { x: number, y: number, w: number, h: number }, rectB: { x: number, y: number, w: number, h: number }): boolean',
    desc: 'Comprobación rápida de intersección booleana entre dos cajas AABB.',
    javascript_code: Spatial.isAABBIntersecting.toString(),
  },
  {
    id: 'fn_getVisibleViewportBounds',
    name: 'getVisibleViewportBounds',
    tags: ['Graphics', 'Spatial'],
    signature: 'getVisibleViewportBounds(camera: { x: number, y: number, zoom: number }, canvasWidth: number, canvasHeight: number, bufferMargin?: number): { x: number, y: number, w: number, h: number }',
    desc: 'Calcula los límites visibles en coordenadas del mundo para frustum culling.',
    javascript_code: Spatial.getVisibleViewportBounds.toString(),
  },
  {
    id: 'fn_ChunkManager',
    name: 'ChunkManager',
    tags: ['WorldChunks', 'GameCore'],
    signature: 'new ChunkManager(chunkSize?: number, tileSize?: number, renderDistance?: number)',
    desc: 'Gestor de streaming infinito de chunks para mundos 2D abiertos.',
    javascript_code: WorldChunks.ChunkManager.toString(),
  },
{
    id: 'fn_mat4Perspective',
    name: 'mat4Perspective',
    tags: ['Math3D', 'Graphics'],
    signature: 'mat4Perspective(out: Float32Array, fovInRad: number, aspect: number, near: number, far: number): Float32Array',
    desc: 'Genera una matriz de proyección en perspectiva de 4x4.',
    javascript_code: Math3D.mat4Perspective.toString(),
  },
  {
    id: 'fn_raycastVoxel',
    name: 'raycastVoxel',
    tags: ['Math3D', 'Physics', 'Voxel'],
    signature: 'raycastVoxel(origin: Float32Array, direction: Float32Array, maxDist: number, world: any): object',
    desc: 'Algoritmo de DDA rápido para intersección de rayos en mundos de bloques 3D.',
    javascript_code: Math3D.raycastVoxel.toString(),
  },
  {
    id: 'fn_VoxelWorld3D',
    name: 'VoxelWorld3D',
    tags: ['WorldChunks3D', 'Voxel'],
    signature: 'new VoxelWorld3D(chunkSize?: number)',
    desc: 'Gestor de datos de chunks 3D e invocador de Culled Mesh Generation.',
    javascript_code: WorldChunks3D.VoxelWorld3D.toString(),
  },
  {
    id: 'fn_createFirstPersonCamera',
    name: 'createFirstPersonCamera',
    tags: ['Physics3D', 'Input'],
    signature: 'createFirstPersonCamera(domElement?: HTMLElement): object',
    desc: 'Cámara en primera persona acoplada con PointerLock API para FPS y Minecraft.',
    javascript_code: Physics3D.createFirstPersonCamera.toString(),
  }
];