export const PAISES = [
  { name: "Alemania", code: "DE", flag: "🇩🇪" },
  { name: "Argentina", code: "AR", flag: "🇦🇷" },
  { name: "Australia", code: "AU", flag: "🇦🇺" },
  { name: "Austria", code: "AT", flag: "🇦🇹" },
  { name: "Bélgica", code: "BE", flag: "🇧🇪" },
  { name: "Bolivia", code: "BO", flag: "🇧🇴" },
  { name: "Brasil", code: "BR", flag: "🇧🇷" },
  { name: "Canadá", code: "CA", flag: "🇨🇦" },
  { name: "Chile", code: "CL", flag: "🇨🇱" },
  { name: "China", code: "CN", flag: "🇨🇳" },
  { name: "Colombia", code: "CO", flag: "🇨🇴" },
  { name: "Costa Rica", code: "CR", flag: "🇨🇷" },
  { name: "Cuba", code: "CU", flag: "🇨🇺" },
  { name: "Dinamarca", code: "DK", flag: "🇩🇰" },
  { name: "Ecuador", code: "EC", flag: "🇪🇨" },
  { name: "Egipto", code: "EG", flag: "🇪🇬" },
  { name: "El Salvador", code: "SV", flag: "🇸🇻" },
  { name: "España", code: "ES", flag: "🇪🇸" },
  { name: "Estados Unidos", code: "US", flag: "🇺🇸" },
  { name: "Francia", code: "FR", flag: "🇫🇷" },
  { name: "Grecia", code: "GR", flag: "🇬🇷" },
  { name: "Guatemala", code: "GT", flag: "🇬🇹" },
  { name: "Honduras", code: "HN", flag: "🇭🇳" },
  { name: "India", code: "IN", flag: "🇮🇳" },
  { name: "Irlanda", code: "IE", flag: "🇮🇪" },
  { name: "Israel", code: "IL", flag: "🇮🇱" },
  { name: "Italia", code: "IT", flag: "🇮🇹" },
  { name: "Japón", code: "JP", flag: "🇯🇵" },
  { name: "Marruecos", code: "MA", flag: "🇲🇦" },
  { name: "México", code: "MX", flag: "🇲🇽" },
  { name: "Nicaragua", code: "NI", flag: "🇳🇮" },
  { name: "Noruega", code: "NO", flag: "🇳🇴" },
  { name: "Nueva Zelanda", code: "NZ", flag: "🇳🇿" },
  { name: "Países Bajos", code: "NL", flag: "🇳🇱" },
  { name: "Panamá", code: "PA", flag: "🇵🇦" },
  { name: "Paraguay", code: "PY", flag: "🇵🇾" },
  { name: "Perú", code: "PE", flag: "🇵🇪" },
  { name: "Polonia", code: "PL", flag: "🇵🇱" },
  { name: "Portugal", code: "PT", flag: "🇵🇹" },
  { name: "Reino Unido", code: "GB", flag: "🇬🇧" },
  { name: "República Dominicana", code: "DO", flag: "🇩🇴" },
  { name: "Rusia", code: "RU", flag: "🇷🇺" },
  { name: "Sudáfrica", code: "ZA", flag: "🇿🇦" },
  { name: "Suecia", code: "SE", flag: "🇸🇪" },
  { name: "Suiza", code: "CH", flag: "🇨🇭" },
  { name: "Turquía", code: "TR", flag: "🇹🇷" },
  { name: "Uruguay", code: "UY", flag: "🇺🇾" },
  { name: "Venezuela", code: "VE", flag: "🇻🇪" }
].sort((a, b) => a.name.localeCompare(b.name));